### ISSUE TITLE
Support verifying diagnostics/fixes in multiple files

### ISSUE THREAD

**Issue by sharwell** [GuOrg/Gu.Roslyn.Asserts#12]
* Some analyzers require multiple input files in order to report diagnostics across multiple files
* Some code fixes involve modifying multiple files and/or creating and/or removing files

These cases should be supported by the test infrastructure.

**Comment by JohanLarsson** [comment]
For multiple files we have:
`public static void Diagnostics<TAnalyzer>(params string[] codeWithErrorsIndicated)`
And
`public static void CodeFix<TAnalyzer, TCodeFix>(IReadOnlyList<string> codeWithErrorsIndicated, string fixedCode, AllowCompilationErrors allowCompilationErrors = AllowCompilationErrors.No)`

Currently no support for changing multiple files so the issue is good.

**Comment by JohanLarsson** [comment]
Should be supported now, leaving open until verified.

**Comment by JohanLarsson** [comment]
Added support for fixes changing multiple documents and or adding documents.
